apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsserver-deployment
  labels:
    app: wsserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wsserver
  template:
    metadata:
      labels:
        app: wsserver
    spec:
      containers:
        - name: wsserver-container
          image: ws.chatapp:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development

---
apiVersion: v1
kind: Service
metadata:
  name: wsserver-service
spec:
  type: NodePort
  selector:
    app: wsserver
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8080
      nodePort: 32000
